<?php
global $connectionodbcx3;

$serverx3='192.168.130.170\SAGE';
$databasex3="basex3";
$userx3="JOVPROD";
$passwordx3="tiger";
$connectionodbcx3 = odbc_connect("Driver={SQL Server};Server=$serverx3;Database=$databasex3;", $userx3, $passwordx3);


$sql ="SELECT SINVOICED.ITMREF_0, SINVOICED.QTY_0, SINVOICED.NETPRI_0, SINVOICED.DISCRGVAL3_0, SINVOICED.DISCRGVAL4_0, SINVOICED.DISCRGVAL5_0, SINVOICED.DISCRGVAL6_0, SINVOICED.VAT_0, SINVOICED.AMTNOTLIN_0, SINVOICEV.INSATI_0, SINVOICEV.INSATI_1, SINVOICEV.INSATI_2, SINVOICEV.INSATI_3, SINVOICEV.SIHORI_0, SINVOICEV.SIHORINUM_0, SINVOICE.AMTATI_0, SINVOICE.AMTTAX_0, SINVOICE.AMTTAX_1, SINVOICE.AMTTAX_2, SINVOICE.AMTTAX_3, SINVOICE.AMTTAX_4, SINVOICE.AMTTAX_5, SINVOICE.AMTTAX_6, SINVOICE.AMTTAX_7, SINVOICE.AMTTAX_8, SINVOICE.AMTTAX_9, SINVOICE.BPR_0, SORDER.VACBPR_0, SINVOICED.ITMDES1_0, TABUNIT.UOM_0, ATEXTRA.TEXTE_0, SDELIVERY.ZBEMAN_0, SDELIVERY.SDHNUM_0, SDELIVERY.SOHNUM_0, GACCDUDATE.PAM_0, GACCDUDATE.TMPCUR_0, GACCDUDATE.PAYCUR_0, GACCDUDATE.AMTCUR_0, GACCDUDATE.DUDDAT_0 FROM SINVOICE INNER JOIN SINVOICEV ON SINVOICE.NUM_0 =SINVOICEV.NUM_0 LEFT JOIN SINVOICED ON SINVOICE.NUM_0 =SINVOICED.NUM_0 LEFT JOIN SORDER ON SINVOICED.SOHNUM_0 = SORDER.SOHNUM_0 LEFT JOIN GACCDUDATE ON SINVOICE.NUM_0 = GACCDUDATE.NUM_0 LEFT JOIN SDELIVERY ON SINVOICED.SDHNUM_0 = SDELIVERY.SDHNUM_0 LEFT JOIN TABUNIT ON SINVOICED.SAU_0 = TABUNIT.UOM_0 LEFT JOIN ATEXTRA ON TABUNIT.UOM_0 = ATEXTRA.IDENT1_0 WHERE SINVOICED.NUM_0='PRF121802100004' AND ATEXTRA.LANGUE_0 = 'FRA' AND ATEXTRA.ZONE_0='DES'";


$result = odbc_exec($connectionodbcx3,$sql);
$row = odbc_fetch_array($result);

print_r($row);
?>